FROM registry.access.redhat.com/ubi8/nodejs-18-minimal:1-86 AS build
USER 0
COPY .env .
COPY package.json .
COPY package-lock.json .
RUN npm install 
COPY src src
COPY public public
RUN npm run build

FROM registry.access.redhat.com/ubi8/nginx-124

USER 0
COPY --from=build /opt/app-root/src/build /tmp/src
RUN chown -R 1001:0 /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble
CMD /usr/libexec/s2i/run

